### ISSUE TITLE
No sample.env?

### ISSUE THREAD

**Issue by Synchro** [Greening-Digital/constellate#113]
I'm trying to install cl8. The readme says:

> all the required environment variables are outlined in sample.env, in the project root

but there is no such file, so I have no idea what to put in the .env file!

**Comment by mrchrisadams** [comment]
hi Marcus! 

Once #114  is merged in, there'll be a `sample.env` you can see, but in the meantime, it should be visible in that branch.

**Comment by mrchrisadams** [comment]
Hi @Synchro I've merged this in now, and you should be able to see a sample env.

https://github.com/Greening-Digital/constellate/blob/master/sample.env

I'm closing this for now, but let me know if you still have questions.
