### ISSUE TITLE
Update to newer libraries

### ISSUE THREAD

**Issue by mrchrisadams** [Greening-Digital/constellate#7]
We have the codebase running under CI, but we still need to review some of the older date deps, and decide about how to update them.

### Priorities

- [x] the most recent stable version of vue we can use
- [x] updating firebase to a recent version

**Comment by rmparr** [comment]
Something to consider: does it make sense to update Firebase to a recent version, based on the level of effort to convert both the front and back end code, or would the time be better spent decoupling from Firebase and having a truly standalone application?

Going through the code, it appears as though most of the breaking changes are related to Firebase (including what it keeping us on Node v10).

**Comment by mrchrisadams** [comment]
Hmm…

I think I'd need a better idea of how much effort it would take to update just vue and not firebase to answer this really.

But it does make sense. It's not a complex schema, after all, but we'd need to look through what the various things we rely on firebase for, to make this decision.

It might be possible to put simple fascade in front of calls we make to it, and if we get the same inputs and outputs, switch it out.

We mainly need:

- auth (email now, but likely slack too)
- email (for passwords and transaction bits)
- storage of profiles

**Comment by rmparr** [comment]
I can't speak to the effort updating the firebase backend, but the npm packages are all modern via PR #11.

As far as the schema goes, it's not very complex to have multiple authentication models (OAuth, email/password) living in the same place. This is a common enough scenario that many solutions exist. Using OAuth (Slack, maybe Mail Chimp, Google, etc.), as much as I dislike it for my own personal use, actually alleviates a lot of concerns, like password resets.

**Comment by mrchrisadams** [comment]
I've updated firebase now, on the server side to support deploys of the cloud functions again.

The code for this was in the PR for #17, and the PR for #19.

As such I'm gonna close this.
