### ISSUE TITLE
Review and implement more sane schema

### ISSUE THREAD

**Issue by mrchrisadams** [Greening-Digital/constellate#8]
The current schema was put together in a hurry, when experimenting with Airtable years ago.

We have a better idea how it's being used, now, and know more, so the task is to clean up the schema, so we can:

- [x] avoid errors related to poorly used types in columns/fields
- [x] allow for exporting to more sensible open source database, like PostgresSQL
- [x] make changes easier in future
- [x] support people removing their own data from constellate without leaving hanging references

The link below shows the schema in use right now:
https://airtable.com/tblEVkEBQIWYpQtj2/viwyk63XIiNezSzyg

**Comment by mrchrisadams** [comment]
Thanks for chattng just now @rmparr,

I'm gonna summarise the key ideas here from our chat.

I've updated the schema now, but we can make the import schema quite a bit simpler. 

column | notes
-- | --
admin | actual boolean this time
visible | actual boolean this time too
tags | comma separated strings – we keep the original version, but downcase, convert special characters internally
photo | If this added, it’s now just a url for a public photo. We import so we can serve different sized versions server-side
email | Required. Users have the option to use it for looking up a gravatar image in-app, and if when we integrate with anything using email addresses like mailchimp, slack, by default we'd use this link users.
phone | assumed to be a mobile. Like for Whatsapp/Signal
twitter | just the username, not the full url
linkedin | again, the name on linkedin. Not the full url
facebook | vanity name again. We add
bio | For long form text. We’d likely try to render this a markdown, to support links and the rest

Below, is what this might look like. We this as a basis for any csv import, and generate linked tag objects for users as part of the import process

name | admin | visible | tags | photo | email | phone | website | twitter | linkedin | facebook | bio
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Bart Simpson | FALSE | TRUE | policy, government |   | bart.simpson@example.com |   |   |   |   |   |  
Sideshow Bob | FALSE | TRUE | design, creative |   | sideshowbob@example.com |   |   |   |   |   |  
Montgomery Burns | TRUE | TRUE | Non-exec director, entrepreneur |   | monty@example.com |   |   |   |   |   |  
Barney Gumble | FALSE | TRUE |   |   | barney@gumble.example.org |   |   |   |   |   |  
Lisa Simpson | FALSE | TRUE | tech, Music, Live Coding |   | lisa@example.com |   |   |   |   |   |  
Gavin Starks | TRUE | TRUE | writing, environment, climate change |   | gavin@hisownwebsite.tld |   |   |   |   |   |  
Christopher Adams | TRUE | FALSE | climate change |   | wave@chrisadams.me.uk |   |   | mrchrisadams | mrchrisadams |   | If you're interested in finding a way to get the entire internet to run on renewable power, I'd like to talk to you.I'm building bits of this constellate thing here, in my spare time, and if you're interested in contributing I'd love to hear even more.
Another Chris Adams | FALSE | TRUE | writing |   | chris@productscience.co.uk |   |   |   |   |   |

**Comment by mrchrisadams** [comment]
I'm gonna park this here - based on on the use case with IB1, and the idea of 'clusters' of users, there's a couple of ways we might do it.

The top one means we end up with a _really_ simple, easy to deploy version of constellate, where you have one deployment per cluster.

This keeps data for each one entirely separate. It means that admins would need to manage each one separately.

If we used oauth or some email-based passwordless system as the primary ways of logging in, then users could exist in multiple separate constellations without too much faffing with passwords. I can imagine this being a [single button deploy with Heroku](https://devcenter.heroku.com/articles/heroku-button), for example.

The second option models the notion of clusters inside a single deployed app, and a single database. This is slightly more centralised, and 

![cl8](https://user-images.githubusercontent.com/17906/85019983-efbf4f80-b16f-11ea-9abd-3c22945134f3.png)

**Comment by rmparr** [comment]
Something to keep in mind with OAuth and multiple deployments is that, due to the callback URL, OAuth would have to be set up for each individual cluster.

In this context, cluster1.ib1.cl8.io cluster2.ib1.cl8.io are separate applications with separate databases, requiring a separate dev keys to authorize. This makes the 'spin up another cluster' scenario more complicated.
